//! Generate deterministic unsigned demo transactions and their policy fields.
//! These are synthetic wire-valid fixtures for local review only; the zero
//! blockhash makes them intentionally non-broadcastable.

use solana_guard::core::base64;
use solana_guard::core::programs::system_program;
use solana_guard::core::pubkey::Pubkey;

fn main() {
    let recipient = Pubkey::new([2u8; 32]);
    let transaction = sol_transfer(1_000_000_000);
    println!(
        "{}",
        serde_json::json!({
            "provenance": "generated by examples/generate_demo_fixture.rs",
            "broadcastable": false,
            "transaction": transaction,
            "intent": {
                "description": "Demo payment",
                "expected_recipient": recipient.to_base58(),
                "expected_mint": null,
                "max_lamports": 1_000_000_000u64,
                "max_token_amount": 0
            }
        })
    );
}

fn sol_transfer(lamports: u64) -> String {
    let from = Pubkey::new([1u8; 32]);
    let to = Pubkey::new([2u8; 32]);
    let system = system_program();
    let mut data = Vec::new();
    data.extend_from_slice(&2u32.to_le_bytes());
    data.extend_from_slice(&lamports.to_le_bytes());
    legacy_tx(&[from, to, system], 2, &[0, 1], &data)
}

fn legacy_tx(account_keys: &[Pubkey], program_index: u8, accounts: &[u8], data: &[u8]) -> String {
    let mut message = vec![1, 0, 0];
    write_shortvec(&mut message, account_keys.len());
    for key in account_keys {
        message.extend_from_slice(key.as_bytes());
    }
    message.extend_from_slice(&[0u8; 32]);
    write_shortvec(&mut message, 1);
    message.push(program_index);
    write_shortvec(&mut message, accounts.len());
    message.extend_from_slice(accounts);
    write_shortvec(&mut message, data.len());
    message.extend_from_slice(data);

    let mut transaction = vec![1];
    transaction.extend_from_slice(&[0u8; 64]);
    transaction.extend_from_slice(&message);
    base64::encode(&transaction)
}

fn write_shortvec(output: &mut Vec<u8>, mut value: usize) {
    loop {
        let mut byte = (value & 0x7f) as u8;
        value >>= 7;
        if value != 0 {
            byte |= 0x80;
        }
        output.push(byte);
        if value == 0 {
            break;
        }
    }
}
